.circleci/config.yml

More node versions used, and enable publishing to npm

ci: update circleci config

---

packages/language-server/api.d.ts
packages/language-server/src/server.ts
packages/language-server/src/ui5-model.ts
packages/language-server/test/ui5-model-spec.ts
packages/semantic-model/api.d.ts
packages/semantic-model/src/api.ts
packages/semantic-model/test/api-negative-spec.ts
packages/semantic-model/test/unit-spec.ts
test-packages/test-utils/src/utils/semantic-model-provider.ts

Set the version on the model directly since the versions in the distribution libraries aren't the same across all libraries.

feat: support SAP UI5 Distribution libraries version 1.71.14

---

package.json
packages/language-server/api.d.ts
packages/language-server/package.json
packages/language-server/src/server.ts
packages/language-server/src/ui5-model.ts
packages/language-server/test/ui5-model-spec.ts
packages/vscode-ui5-language-assistant/src/extension.ts
yarn.lock

Download and cache UI5 resources in the plugin's globalStoragePath instead of downloading it again on every plugin activation.

perf(language-server): cache downloaded resources

---

packages/language-server/src/completion-items.ts
packages/language-server/test/completion-items-spec.ts

If the namespace of the class is not defined.
In case of collision add number suffix to the inserted name.

feat(language-server): auto-insert namespace when selecting class

---

packages/language-server/src/xml-view-diagnostics.ts
packages/language-server/test/snapshots/xml-view-diagnostics/unknown-tag-name/input.xml
packages/language-server/test/snapshots/xml-view-diagnostics/unknown-tag-name/output-lsp-response.json
packages/logic-utils/api.d.ts
packages/logic-utils/src/api.ts
packages/logic-utils/src/utils/xml-node-to-ui5-node.ts
packages/logic-utils/test/utils/xml-node-to-ui5-node-spec.ts
packages/xml-views-validation/api.d.ts
packages/xml-views-validation/src/utils/messages.ts
packages/xml-views-validation/src/validators/elements/unknown-tag-name.ts
packages/xml-views-validation/src/validators/elements/use-of-deprecated-class.ts
packages/xml-views-validation/src/validators/index.ts
packages/xml-views-validation/test/test-utils.ts
packages/xml-views-validation/test/validators/attributes/unknown-attribute-key-spec.ts
packages/xml-views-validation/test/validators/element/unknown-tag-name-spec.ts

~~**Note:** this is built on top of the unknown attribute PR (#120) because it re-uses some of it. Do not merge until that PR is merged and this PR is rebased.~~

Validate unknown tag

---

packages/xml-views-validation/src/validators/elements/type-of-aggregation.ts
packages/xml-views-validation/test/validators/element/type-of-aggregation-spec.ts
tsconfig.json

fix(xml-views-validation): Fragments in aggregations can cause a false positive

---

packages/vscode-ui5-language-assistant/test/run-integration-tests.ts
packages/vscode-ui5-language-assistant/test/suite/validations/flex-disabled/flex-disabled-spec.ts
packages/vscode-ui5-language-assistant/test/suite/validations/flex-enabled/flex-enabled-spec.ts

test: disable VSCode tests

---

.circleci/config.yml
packages/xml-views-validation/src/validators/elements/unknown-tag-name.ts
packages/xml-views-validation/test/validators/element/unknown-tag-name-spec.ts

fix(xml-views-validation): enable correct sap.ui.core.ExtensionPoint validation
Fixes: https://github.com/SAP/ui5-language-assistant/issues/387

Enable correct sap.ui.core.ExtensionPoint validation

---

.circleci/config.yml
.husky/commit-msg
.husky/pre-commit
.husky/skip.js
package.json
yarn.lock

build(deps-dev): upgrade to husky 8.0.1

---

packages/logic-utils/src/utils/documentation.ts
packages/logic-utils/test/utils/documentation-spec.ts

fix(language-server): ensure proper urls for topic links

---

package.json
packages/context/src/ui5-model.ts
packages/context/src/ui5-yaml.ts
packages/context/src/utils/ui5.ts
packages/context/src/watcher.ts
packages/context/test/loader-spec.ts
packages/context/test/manifest-spec.ts
packages/context/test/services-spec.ts
packages/context/test/ui5-model-spec.ts
packages/context/test/utils/project-spec.ts
packages/context/test/watcher-spec.ts
yarn.lock

Issue: #557 
FIxed OpenUI5 version loading issue and fixed ui5.yaml file changes handler

fix: wrong version negotiation for OpenUI5 framework

---

.changeset/tame-days-sing.md
packages/vscode-ui5-language-assistant/CHANGELOG.md

A version update and changelog update is required for modules that have been affected by the implementation of offline mode support.

feat: version bump for the offline mode related packages

---

.changeset/honest-seas-tap.md
package.json
packages/fe/test/services/completion/providers/context-path-spec.ts
packages/fe/test/services/completion/providers/filter-bar-spec.ts
packages/fe/test/services/completion/providers/meta-path-spec.ts
packages/language-server/package.json
packages/language-server/src/server.ts
packages/logic-utils/api.d.ts
packages/logic-utils/src/api.ts
packages/logic-utils/src/utils/document.ts
packages/logic-utils/test/utils/document-spec.ts
packages/settings/api.d.ts
packages/settings/src/settings.ts
packages/settings/test/settings-spec.ts
packages/vscode-ui5-language-assistant/.vscodeignore
packages/vscode-ui5-language-assistant/esbuild.js
packages/vscode-ui5-language-assistant/package.json
packages/vscode-ui5-language-assistant/scripts/package-vsix.js
packages/vscode-ui5-language-assistant/src/constants.ts
packages/vscode-ui5-language-assistant/src/extension.ts
packages/vscode-ui5-language-assistant/src/formatter/document.ts
packages/vscode-ui5-language-assistant/src/formatter/index.ts
yarn.lock

Enable formatting for `.view.xml` or `.fragment.xml` files

feat: enable formatting

---

.changeset/shaggy-houses-scream.md
README.md
packages/vscode-ui5-language-assistant/README.md

Fixed bug - updates were done in wrong README file

fix: readme content correction

---

.changeset/sweet-clouds-remain.md
lerna.json
package.json
packages/context/test/unit/ui5-model.test.ts
test-packages/framework/projects/cap/package.json
yarn.lock

Lerna version upgrade to fix npm deployment in GitHub action

fix: lerna upgrade

---

.changeset/stupid-zoos-mate.md
packages/binding/src/api.ts
packages/binding/src/definition/definition.ts
packages/binding/src/services/hover/index.ts
packages/binding/src/utils/documentation.ts
packages/binding/src/utils/index.ts
packages/binding/test/unit/definition/__snapshots__/definition.test.ts.snap
packages/binding/test/unit/helper.ts
packages/binding/test/unit/services/completion/__snapshots__/index.test.ts.snap
packages/binding/test/unit/services/hover/__snapshots__/hover.test.ts.snap
packages/binding/test/unit/services/hover/hover.test.ts
packages/language-server/src/hover.ts

Add hover support for property binding

feat: hover support for proeprty binding

---

.changeset/quiet-stingrays-hug.md
packages/binding-parser/src/utils/expression.ts
packages/binding-parser/test/unit/utils/expression.test.ts
packages/binding/src/api.ts
packages/binding/src/constant.ts
packages/binding/src/definition/definition.ts
packages/binding/src/services/completion/providers/property-binding-info.ts
packages/binding/src/services/diagnostics/validators/check-key.ts
packages/binding/src/services/diagnostics/validators/property-binding-info-validator.ts
packages/binding/src/services/hover/index.ts
packages/binding/test/unit/services/completion/__snapshots__/index.test.ts.snap
packages/binding/test/unit/services/completion/index.test.ts
packages/binding/test/unit/services/diagnostics/validators/__snapshots__/property-binding-info-validator.test.ts.snap
packages/binding/test/unit/services/diagnostics/validators/property-binding-info-validator.test.ts
packages/binding/test/unit/services/hover/__snapshots__/hover.test.ts.snap
packages/binding/test/unit/services/hover/hover.test.ts
packages/vscode-ui5-language-assistant/src/utils/binding-semantic-token-creator.ts
packages/vscode-ui5-language-assistant/test/unit/binding-semantic-token-provider.test.ts
packages/vscode-ui5-language-assistant/test/unit/utils/binding-semantic-token-creator.test.ts

link to issue: https://github.com/SAP/ui5-language-assistant/issues/652
Relax check for `isBindingAllowed`
Support ui5object a special marker

fix: enhance check for binding expression

---

.changeset/proud-timers-battle.md
.github/workflows/deploy_maual.yaml
.github/workflows/release.yaml
package.json
yarn.lock

fix: github actions fix

---

.changeset/lovely-dragons-appear.md
packages/binding-parser/src/lexer/token.ts
packages/binding-parser/test/unit/parser/binding-parser.test.ts
packages/language-server/src/server.ts
packages/vscode-ui5-language-assistant/src/extension.ts

Fixed SonarCloud check complaints

fix: sonar complaints fix

---

.changeset/new-jeans-crash.md
packages/logic-utils/src/utils/type-to-string.ts
packages/semantic-model-types/api.d.ts
packages/semantic-model/src/convert.ts
packages/semantic-model/src/resolve.ts
packages/semantic-model/test/unit/unit.test.ts
test-packages/test-utils/api.d.ts
test-packages/test-utils/src/api.ts
test-packages/test-utils/src/utils/semantic-model-provider.ts

Issue: https://github.com/SAP/ui5-language-assistant/issues/694

fix: semantic model for UI5, starting from version 1.121.0

---

.changeset/clean-beans-cough.md
packages/context/api.d.ts
packages/context/test/unit/ui5-model.test.ts
packages/language-server/src/server.ts
test-packages/test-utils/src/utils/download-ui5-resources.ts

Fix reference. This issue introduced due to this change. https://github.com/SAP/ui5-language-assistant/pull/721

fix: reference

---

.changeset/unlucky-items-fly.md
packages/language-server/jest.config.js
packages/language-server/scripts/update-diagnostics-snapshots.js
packages/language-server/src/server.ts
packages/vscode-ui5-language-assistant/jest.config.js
packages/vscode-ui5-language-assistant/package.json
packages/vscode-ui5-language-assistant/scripts/package-vsix.js
packages/vscode-ui5-language-assistant/src/extension.ts
sonar-project.properties

This PR
* activate extension only for `.view.xml` or `.fragment.xml` file
* add provider/service to `context.subscriptions` - helps in clean up
This PR is cherry pick of https://github.com/SAP/ui5-language-assistant/pull/718

refactor: optimization of activation processing
