SAP/ui5-language-assistant

- packages/language-server/test/completion-items-spec.ts
- packages/xml-views-completion/src/providers/attributeValue/namespace.ts
- packages/xml-views-completion/test/providers/attributeValue/namespace-spec.ts
Before the entire value was used even if the cursor was in the middle of the existing value.
Remove redundant test after bug fix.
> fix: use prefix when suggesting namespaces in attribute value

- packages/language-server/test/completion-items-spec.ts
- packages/language-server/test/completion-items-utils.ts
- packages/language-server/test/copmletion-items-classes-spec.ts
The tests did not change except for one test that uses a new utility function to get the range for the `additionalTextEdits`:
`"will insert the namespace when selecting completion for class in inner tag and namespace is not defined"`
Utility functions moved to their own file.
Changes to utility functions:
* Added assertion that text edits don't overlap (`assertRangesDoNotOverlap`)
* Added model parameter to `getSuggestions` (since it's no longer in a closure)
* Added handling of `additionalTextEdits` ranges in `getSuggestions` 
* Added function `getRanges`
* Extracted function `getXmlSnippetDocument` from `getSuggestions`
> refactor(language-server): move classes code completion tests to other file

- packages/semantic-model/test/api-spec.ts
temp workaround, root problem is due to cyclic dep between semantic-model(devDep) and
test-utils(dep)
> test(semantic-model): model generation timeouts not working workaround

- packages/xml-views-validation/src/validators/attributes/unknown-xmlns-namespace.ts
Instead of checking the library names, check all namespaces under "sap".
> fix: check unknown namespaces according to the defined namespaces

- packages/semantic-model/src/fix-api-json.ts
- test-packages/test-utils/src/utils/semantic-model-provider.ts
Remove it from its "implements" array when building the model.
Note: I didn't add tests since the strict model building tests already check this (I removed the same fix from the test code).
> fix: remove message for "sap.ui.vk.BaseNodeProxy" on library startup

- packages/language-server/src/documentation.ts
- packages/language-server/test/snapshots/xml-view-diagnostics/use-of-deprecated-class/output-lsp-response.json
- packages/logic-utils/api.d.ts
- packages/logic-utils/src/api.ts
- packages/logic-utils/src/utils/documentation.ts
- packages/logic-utils/test/utils/documentation-spec.ts
- packages/xml-views-validation/src/utils/deprecated-message-builder.ts
- packages/xml-views-validation/src/validators/elements/use-of-deprecated-class.ts
- packages/xml-views-validation/test/utils/deprecated-message-builder-spec.ts
- packages/xml-views-validation/test/validators/element/use-of-deprecated-class-spec.ts
- test-packages/test-utils/api.d.ts
- test-packages/test-utils/src/utils/semantic-model-builder.ts
Move some documentation functions to logic-utils and add tests
> fix: use shorter description without jsdoc tags in deprecation warning

- packages/language-server/src/completion-items.ts
- packages/language-server/test/completion-items-classes-spec.ts
- packages/language-server/test/completion-items-spec.ts
- packages/language-server/test/hover-spec.ts
- packages/language-server/test/snapshots/xml-view-diagnostics/unknown-attribute-key/input.xml
- packages/language-server/test/snapshots/xml-view-diagnostics/unknown-attribute-key/output-lsp-response.json
- packages/language-server/test/snapshots/xml-view-diagnostics/unknown-tag-name/input.xml
- packages/language-server/test/snapshots/xml-view-diagnostics/unknown-tag-name/output-lsp-response.json
- packages/logic-utils/api.d.ts
- packages/logic-utils/src/api.ts
- packages/logic-utils/src/utils/split-qname.ts
- packages/logic-utils/src/utils/xml-namespaces.ts
- packages/logic-utils/src/utils/xml-node-to-ui5-node.ts
- packages/logic-utils/src/utils/xml-to-fqn.ts
- packages/logic-utils/test/utils/split-qname-spec.ts
- packages/logic-utils/test/utils/xml-namespaces-spec.ts
- packages/logic-utils/test/utils/xml-node-to-ui5-node-spec.ts
- packages/vscode-ui5-language-assistant/test/suite/extension-spec.ts
- packages/xml-views-completion/src/providers/elementName/aggregation.ts
- packages/xml-views-completion/test/providers/elementName/aggregation-spec.ts
- packages/xml-views-completion/test/providers/elementName/classes-spec.ts
- packages/xml-views-tooltip/src/tooltip.ts
- packages/xml-views-tooltip/test/tooltip-spec.ts
- packages/xml-views-validation/src/utils/messages.ts
- packages/xml-views-validation/src/validators/attributes/unknown-attribute-key.ts
- packages/xml-views-validation/src/validators/elements/unknown-tag-name.ts
- packages/xml-views-validation/test/validators/attributes/unknown-attribute-key-spec.ts
- packages/xml-views-validation/test/validators/element/unknown-tag-name-spec.ts
- packages/xml-views-validation/test/validators/element/use-of-deprecated-class-spec.ts
Aggregation tags must have the same namespace as their parent control tag.
This is now supported in code completion, validations and hover.
Additionally, don't filter out the current aggregation during code completion.
> fix: support namespace in aggregation name

- packages/xml-views-completion/src/providers/elementName/classes.ts
- packages/xml-views-completion/test/providers/elementName/classes-spec.ts
Use utility function to split the element name and namespace prefix.
> fix: don't offer classes from sub-namespaces in code completion

- packages/xml-views-validation/test/validators/document/non-unique-id-spec.ts
Also use `getMessage` to build expected messages to reduce TCO
> test(xml-views-validations): add missing test to non-unique-ids

- packages/vscode-ui5-language-assistant/package.json
same as used in the schemaStore.
> chore: use raw.githubusercontent.com for manifet.json schema

- .gitignore
Add sub-packages LICENSE to gitignore as they are generated during build.
> chore: add sub-packages LICENSE to gitignore

- .circleci/config.yml
The latest version https://github.com/tcnksm/ghr@v0.15.0 fails.
Therefore we rollback to https://github.com/tcnksm/ghr@v0.14.0.
> build(deploy-ghr): use specific go script ghr@v0.14.0

- packages/logic-utils/src/utils/flatten-members.ts
- packages/logic-utils/test/utils/flatten-property-spec.ts
Controls that override the inherited properties had duplicate completion items for attribute names e.g. https://ui5.sap.com/1.102.0/#/api/sap.fe.macros.FilterBar.
Changed `flattenMembers` function to return only unique members (by name).
> fix: duplicate code completion items

- .circleci/config.yml
- .mocharc.js
- package.json
- packages/language-server/package.json
- webpack.config.base.js
- yarn.lock
Fixes #513.
- Removes `vscode-languageserver-types` version mismatch
- Updates `lerna` to the latest version
- Updated `webpack` to latest version and removed `--openssl-legacy-provider` flag
- Changed `webpack` file name hashing algorithm https://github.com/webpack/webpack/issues/14532
- Updated node images
- Increased test timeout due to multiple failures when downloading UI5 library data
> chore: update dependencies

- packages/context/src/ui5-model.ts
- packages/context/test/ui5-model-spec.ts
- packages/language-server/src/server.ts
- packages/semantic-model-types/api.d.ts
- packages/semantic-model/api.d.ts
- packages/semantic-model/src/api.ts
- packages/vscode-ui5-language-assistant/src/extension.ts
Make the implementation more robust and provide additional diagnostics for
- UI5 version is not available in the project manifest.json ->Notify the user about fallback to default
- UI5 version available in project, but api.json is not available (old or wrong versions case)
> fix: show ui diagnostics if minUI5 version undefined in manifest.json or unsupported

- packages/language-server/src/server.ts
Currently if an `.view.xml` or `.fragment.xml` is closed, its diagnostic is not cleared out. This will clear out diagnostics of an `.view.xml` or `.fragment.xml` file.
> fix: clear diagnostics for a closed file

- .circleci/config.yml
publishing to github fails due to go lang version.
> ci: fix ghr publish job

- packages/context/src/manifest.ts
- packages/context/test/manifest-spec.ts
Fixes #552
Added additional checks to avoid crashing if default model (with name "") does not exist.
> fix: crash with no default model

- packages/context/src/utils/project.ts
- packages/context/test/utils/project-spec.ts
Issue: #556
When trying to resolve project root, we were looking for SAP Fiori elements applications by default and if it failed then free style applications were ignored. Now we look for any application by default.
> fix: project root resolution

- packages/context/package.json
- yarn.lock
Issue: #555 
Bump `@sap-ux/project-access` package to latest version, where issue with multiple documents in `ui5.yaml` files is fixed.
> fix: crash when ui5.yaml has multiple documents

- packages/xml-views-completion/src/providers/elementName/classes.ts
- packages/xml-views-completion/test/providers/elementName/classes-spec.ts
Issue: #564 
Since `sap.ui.core.FragmentDefinition` is not defined in api.json, we need to add custom logic to handle this case.
> fix: completion in FragmentDefinition

- .changeset/funny-tables-impress.md
- package.json
Publishing github action is unable to detect changes. This pr contains fix for lerna publish command which is used in the workflow
> fix: npm publish fix

- .github/workflows/deploy_maual.yaml
Environment variable added to npm deployment script
> fix: environment for publishing

- .changeset/eleven-items-turn.md
- packages/binding/src/services/completion/providers/create-value.ts
- packages/binding/src/services/completion/providers/property-binding-info.ts
- packages/binding/src/services/diagnostics/validators/check-brackets.ts
- packages/binding/src/services/diagnostics/validators/check-collection-value.ts
- packages/binding/src/services/diagnostics/validators/check-key.ts
- packages/binding/src/services/diagnostics/validators/issue-collector.ts
- packages/binding/src/services/diagnostics/validators/property-binding-info-validator.ts
- packages/binding/src/types/cursor.ts
- packages/binding/src/types/index.ts
- packages/binding/src/types/issues.ts
- packages/binding/src/utils/cursor.ts
- packages/binding/test/unit/services/completion/index.test.ts
- packages/binding/test/unit/services/diagnostics/validators/property-binding-info-validator.test.ts
- packages/binding/test/unit/utils/cursor.test.ts
This PR address following points:
* No diagnostic for empty bracket with unknown char e.g `<Text text="{!!!}" id="test-id"/>`
* No duplicate or wrong code completion for multiple binding e.g `<Text text="some text and {} some here {parts: [|]}" id="test-id"/>`
* Add diagnostic for missing key e.g `<Text text="{:'', formatter: '.methodName'}" id="test-id"/>`
* Add diagnostic for missing bracket eg. `{path: ''` , `parts: [''` or `parts: [{path: '']` 
* Correct completion for collection
a. `<Text text="{ parts: |[{}] }" id="test-id"/>` - no completion item(s)
b. `<Text text="{ parts: [{}]| }" id="test-id"/>` - no completion item(s)
c. `<Text text="{ parts: [|{}] }" id="test-id"/>`
d. `<Text text="{ parts: [{}|] }" id="test-id"/>`
e. `<Text text="{ parts: [''|] }" id="test-id"/>`
f. `<Text …
> Fix: some issues

- .changeset/empty-balloons-repeat.md
- packages/binding/src/services/completion/index.ts
- packages/binding/src/services/completion/providers/create-all-supported-elements.ts
- packages/binding/src/services/completion/providers/create-initial-snippet.ts
- packages/binding/src/services/completion/providers/create-key-value.ts
- packages/binding/src/services/diagnostics/validators/property-binding-info-validator.ts
- packages/binding/src/utils/index.ts
- packages/binding/src/utils/logger.ts
- packages/binding/test/unit/services/completion/__snapshots__/index.test.ts.snap
- packages/binding/test/unit/services/completion/index.test.ts
Background:
VSCode-Insider (version: 1.80.0-insider (Universal)) shuts down completely completion item request if there is a completion item with choices and user select this item. Subsequent completion item request will not work. 
Choices are just fine to keep, but there is one another usability  issue with them. Choice does not support tab stop. To get around with VSCode issue and choice restriction, choice option is removed from completion item for property binding info.
> fix: remove choice

- .changeset/shiny-maps-guess.md
- packages/binding-parser/src/api.ts
- packages/binding-parser/src/lexer/token.ts
- packages/binding-parser/src/types/binding-parser.ts
- packages/binding-parser/src/utils/expression.ts
- packages/binding-parser/src/utils/index.ts
- packages/binding-parser/test/unit/utils/expression.test.ts
- packages/binding/src/services/completion/providers/property-binding-info.ts
- packages/binding/src/services/diagnostics/validators/property-binding-info-validator.ts
- packages/binding/src/utils/cursor.ts
- packages/binding/src/utils/expression.ts
- packages/binding/src/utils/index.ts
- packages/binding/test/unit/services/diagnostics/validators/property-binding-info-validator.test.ts
- packages/binding/test/unit/utils/expression.test.ts
fix unjustified error for following points.
* escape diagnostic for metadata binding that contains colon e.g `{/SomeValue/#@sap:label}`
* consider also HTML equivalent e.g. `&#47;` or `&#x2F;`
* escape diagnostic for model that contains colon e.g https://github.com/SAP/ui5-language-assistant/issues/637
*   consider also HTML equivalent `&gt;`
Refactoring
* move some logic to `binding-parser` package for reuse
> fix: unjustified errors for property binding info

- .changeset/cuddly-laws-train.md
- .github/workflows/deploy_maual.yaml
- package.json
- yarn.lock
The new version of lerna is causing release to npmjs to faile. See  https://github.com/SAP/ui5-language-assistant/actions/runs/6348139648/job/17244500931
Anyhow, it might be that root cause lays in `nx` module that is consumed by `lerna`
> fix: use fixed version of lerna

- .changeset/smooth-socks-raise.md
- packages/vscode-ui5-language-assistant/src/manifest/schema.json
Related issue: https://github.com/SAP/ui5-language-assistant/issues/691
Updated `schema.json` file. This is needed for off line work.
> Chore: update schema

- .changeset/nice-news-talk.md
- packages/fe/src/i18n/i18n.json
- packages/fe/test/unit/services/diagnostics/validators/missing-entity-set.test.ts
Corrected text of one of the warning messages related to metapath validation
> fix: warning text correction

- .changeset/unlucky-ants-burn.md
- packages/binding/package.json
- packages/context/package.json
- packages/context/src/api.ts
- packages/context/src/types.ts
- packages/context/test/unit/api.test.ts
- packages/context/test/unit/ui5-model.test.ts
- packages/fe/package.json
- packages/fe/test/unit/utils/metadata.test.ts
- packages/fe/test/unit/utils/path.test.ts
- packages/vscode-ui5-language-assistant/src/manifest/schema.json
- test-packages/test-utils/api.d.ts
- test-packages/test-utils/src/api.ts
- test-packages/test-utils/src/utils/semantic-model-provider.ts
- yarn.lock
issue: https://github.com/SAP/ui5-language-assistant/issues/715
> fix: min ui5 version as array

- .changeset/few-rules-raise.md
- packages/vscode-ui5-language-assistant-bas-ext/package.json
To be able to publish to [npm.js ](https://www.npmjs.com/package/@ui5-language-assistant/vscode-ui5-language-assistant-bas-ext?activeTab=versions) version of `"@ui5-language-assistant/vscode-ui5-language-assistant-bas-ext"` must be sync with `"vscode-ui5-language-assistant"`. In last PR, it was forgotten to include it in change set.
> fix: support `minUI5Version` as an array

- .changeset/thick-trains-doubt.md
- packages/language-server/test/unit/snapshots/xml-view-diagnostics/non-unique-id/options.js
- packages/xml-views-validation/package.json
- packages/xml-views-validation/src/validators/non-unique-id.ts
- packages/xml-views-validation/test/unit/validators/non-unique-id.test.ts
> fix: file uri for windows

- .changeset/nasty-bugs-chew.md
- packages/context/src/adp-manifest.ts
- packages/context/src/api.ts
- packages/context/src/utils/view-files.ts
- packages/context/test/unit/adp-manifest.test.ts
- packages/context/test/unit/api.test.ts
- packages/context/test/unit/loader.test.ts
- packages/context/test/unit/utils/view-files.test.ts
- packages/language-server/package.json
- packages/language-server/test/unit/__snapshots__/xml-view-diagnostics.test.ts.snap
- packages/language-server/test/unit/xml-view-diagnostics.test.ts
- packages/vscode-ui5-language-assistant/test/manual-tests/unique-control-ids.md
- test-packages/framework/projects/adp.test/.gitignore
- test-packages/framework/projects/adp.test/AppVariant_index.html
- test-packages/framework/projects/adp.test/README.md
- test-packages/framework/projects/adp.test/package.json
- test-packages/framework/projects/adp.test/ui5.yaml
- test-packages/framework/projects/adp.test/webapp/changes/fragments/actionToolbar.fragment.xml
- test-packages/framework/projects/adp.test/webapp/changes/fragments/filterBar.fragment.xml
- test-packages/framework/projects/adp.test/webapp/changes/id_1728329677838_297_addXML.change
- test-packages/framework/projects/adp.test/webapp/changes/id_1728329742822_298_addXML.change
- test-packages/framework/projects/adp.test/webapp/i18n/i18n.properties
- test-packages/framework/projects/adp.test/webapp/manifest.appdescr_variant
- test-packages/framework/src/types.ts
This PR solves
* https://github.com/SAP/ui5-language-assistant/issues/732
* Add LSP support for adaptation project - first iteration
* Add manual test case for adaption use case - diagnostics for duplicate ids
* Add adaption test project
> fix: lsp for adaption project - first iteration
